; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native
test_framework = unity
build_flags = 
    -std=gnu++17
    -D NATIVE_TESTING
    -I test/native_include
lib_deps = 
    fabiobatsilva/ArduinoFake@^0.4.0
lib_compat_mode = off

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
test_framework = unity
lib_ignore = ArduinoFake
board_build.partitions = ota_partitions.csv
lib_deps = tzapu/WiFiManager@^2.0.17
